title: Iain Dillingham
description: My website
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Iain Dillingham
